### ISSUE TITLE
安装link报错

### ISSUE THREAD

**Issue by StevenZhangHl** [ant-design/antd-mobile-samples#87]
windows系统下执行react-native link @ant-design/icons-react-native
报错如下：
C:\Users\Zealience\AwesomeProject\android>react-native link @ant-design/icons-react-native
rnpm-install info Linking assets to ios project
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null 
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'pbxprojPath' of null

TypeError: Cannot read property 'pbxprojPath' of null
    at Object.linkAssetsIOS [as copyAssets] (C:\Users\Zealience\AwesomeProject\android\node_modules\react-native\local-cli\link\ios\copyAssets
.js:23:47)
    at Object.keys.forEach.platform (C:\Users\Zealience\AwesomeProject\android\node_modules\react-native\local-cli\link\link.js:104:16)
    at Array.forEach (<anonymous>)
    at linkAssets (C:\Users\Zealience\AwesomeProject\android\node_modules\react-native\local-cli\link\link.js:94:32)
    at tasks.push (C:\Users\Zealience\AwesomeProject\android\node_modules\react-native\local-cli\link\link.js:171:20)

**Comment by soakit** [comment]
+1
